# **NUMPY DİZİLERİ**

In [ ]:
import numpy as np

In [ ]:
#!pip install numpy #bu satır eğer numpy indirilmemişse yazılır. indirmek için

In [ ]:
my_list=[10,20,30,40]

In [ ]:
type(my_list)

list

In [ ]:
np.array(my_list)

array([10, 20, 30, 40])

In [ ]:
my_numpy_array = np.array(my_list)

In [ ]:
type(my_numpy_array)

numpy.ndarray

In [ ]:
my_numpy_array.max()

np.int64(40)

In [ ]:
np.ones(5) # beş tane birli array oluşturacak

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.random.random(5)

array([0.2479793 , 0.93482554, 0.04939186, 0.53840067, 0.93712483])

# **ARRAY ARITMETIC (Dizi aritmetiği)**

In [ ]:
my_list1 = [1,2]

In [ ]:
my_list2 = [2,3]

In [ ]:
my_list1+my_list2

[1, 2, 2, 3]

In [ ]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)

In [ ]:
my_numpy_array1+my_numpy_array2 #normal listteki gibi sadece toplamıyor. burada elemanları indexler yoluyla topluyor.1

array([3, 5])

In [ ]:
my_numpy_array1*my_numpy_array2

array([2, 6])

In [ ]:
my_numpy_array1-my_numpy_array2

array([-1, -1])

In [ ]:
my_numpy_array1/my_numpy_array2

array([0.5       , 0.66666667])

In [ ]:
my_numpy_array1

array([1, 2])

In [ ]:
my_numpy_array1*5 #yani aslında index mantığı ile çalışıyor

array([ 5, 10])

In [ ]:
my_list1*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [ ]:
other_array = np.array([10,20,30,40,50])

In [ ]:
other_array.min()

np.int64(10)

In [ ]:
other_array.sum()

np.int64(150)

In [ ]:
my_numpy_array1

array([1, 2])

In [ ]:
other_array

array([10, 20, 30, 40, 50])

In [ ]:
#my_numpy_array1+other_array #aynı index sayısına sahip değiller bu yüzden hata verecek

# **INDEXING & ARANGE**

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np_array = np.arange(0,10)

In [ ]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_array[0]

np.int64(0)

In [ ]:
np_array[-1]

np.int64(9)

In [ ]:
np_array[1:4:]

array([1, 2, 3])

In [ ]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np_array[2:6:2]

array([2, 4])

In [ ]:
#random

In [ ]:
np.random.randn(4)

array([ 0.36735283,  0.9503098 , -0.72995089,  1.32408672])

In [ ]:
np.random.randn(4,4)

array([[-0.23898192,  0.14850579,  1.28471281, -0.64324041],
       [-0.99447891, -0.18326206,  0.6346416 ,  1.42826516],
       [-0.96928149, -1.84498585, -1.55097712,  0.37508959],
       [ 0.93053615, -0.43046651,  0.62561665, -1.02515982]])

In [ ]:
np.random.randint(1,300,5) #bir ile 300 arasında beş tane rastgele sayı verecek

array([180,  68,  34,  50, 292])