# **NUMPY MATRICES**

In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][1]

10

In [7]:
# row * Column

In [8]:
numpy_matrix = np.array([[5,10],[15,20]])

In [9]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [10]:
numpy_matrix[1][0]

np.int64(15)

In [17]:
numpy_matrix.sum()

np.int64(50)

In [18]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.random.random((3,2))

array([[0.65245674, 0.47158394],
       [0.52947954, 0.4528328 ],
       [0.74462546, 0.63703012]])

In [22]:
# matrix aritmetic

In [23]:
first_array = np.array([[10,20],[30,40]])

In [24]:
second_array = np.array([[5,15],[25,35]])

In [26]:
first_array + second_array #summing by indexes

array([[15, 35],
       [55, 75]])

In [27]:
first_array

array([[10, 20],
       [30, 40]])

In [28]:
third_array = np.array([[50,60]])

In [29]:
third_array

array([[50, 60]])

In [31]:
first_array+third_array #third array first arrayin ilk ve ikinci satırına eklenecek

array([[ 60,  80],
       [ 80, 100]])

In [32]:
fourth_array = np.array([[10,20,30,40,50]])

In [34]:
#first_array+fourth_array # hiç bir şekilde uymuyor error verecek bu nedenl

In [35]:
first_array*2

array([[20, 40],
       [60, 80]])

In [36]:
first_array/4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [37]:
third_array = np.array([[10],[20]])

In [38]:
third_array

array([[10],
       [20]])

In [39]:
third_array.shape

(2, 1)

In [40]:
first_array.shape

(2, 2)

In [41]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [42]:
first_array

array([[10, 20],
       [30, 40]])

# **Matrix çarpımı MATRİX MULTIPLICATION (sadece NumPy'da)**

In [46]:
first_array


array([[10, 20],
       [30, 40]])

In [47]:
second_array

array([[ 5, 15],
       [25, 35]])

In [43]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [48]:
#dot product

In [49]:
first_matrix = np.array([[10,20,30]])

In [50]:
first_matrix

array([[10, 20, 30]])

In [52]:
first_matrix.shape

(1, 3)

In [53]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [54]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [56]:
second_matrix.shape # shape gives you the matrix size

(3, 2)

In [58]:
#first_matrix*second_matrix # bunu yapamayız hata verir

In [60]:
result_matrix = first_matrix.dot(second_matrix)

In [62]:
result_matrix.shape

(1, 2)