In [5]:
import numpy as np

In [10]:
new_array = np.random.randint(1,100,20)

In [13]:
new_array

array([12, 35, 76, 83, 12, 30, 28,  3, 25, 36, 99, 61, 17, 58, 98, 51,  4,
       28, 46, 37])

In [14]:
new_array > 25

array([False,  True,  True,  True, False,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True])

In [15]:
new_array[new_array > 25]

array([35, 76, 83, 30, 28, 36, 99, 61, 58, 98, 51, 28, 46, 37])

In [16]:
new_array[new_array < 25]

array([12, 12,  3, 17,  4])

In [17]:
#TRANSPOSE & RESHAPE

In [18]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [19]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [20]:
matrix_array.shape

(3, 2)

In [23]:
matrix_array.transpose() #turn the rows into columns

array([[10, 20, 30],
       [20, 30, 40]])

In [25]:
matrix_array.T #different syntax

array([[10, 20, 30],
       [20, 30, 40]])

In [26]:
random_array = np.random.random((6,1))

In [27]:
random_array

array([[0.13058418],
       [0.32052133],
       [0.21403352],
       [0.4627354 ],
       [0.1101682 ],
       [0.49698449]])

In [28]:
random_array.shape

(6, 1)

In [29]:
random_array.reshape(2,3)

array([[0.13058418, 0.32052133, 0.21403352],
       [0.4627354 , 0.1101682 , 0.49698449]])

In [30]:
random_array.reshape(3,2)

array([[0.13058418, 0.32052133],
       [0.21403352, 0.4627354 ],
       [0.1101682 , 0.49698449]])

In [31]:
# z-score

In [32]:
data = np.array([10,12,13,15,18,25,100,105])

In [33]:
#outlier

In [34]:
mean = np.mean(data)

In [35]:
mean

np.float64(37.25)

In [36]:
data.sum() / len(data)

np.float64(37.25)

In [38]:
std = np.std(data) #standart sapma

In [39]:
std

np.float64(37.9333296719389)

In [40]:
z_scores = (data - mean) / std

In [41]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [42]:
z_scores[z_scores > 1]

array([1.65421809, 1.78602829])

In [43]:
data[z_scores > 1]

array([100, 105])

In [44]:
#MATH EQUATIONS

In [51]:
#2x + 3y = 8 and 5x + 7y = 19

In [52]:
A = np.array([[2,3],[5,7]]) #coefficient

In [53]:
B = np.array([8,19]) #constant

In [54]:
soultion = np.linalg.solve(A,B) # linalg = linear algebra

In [56]:
soultion # x=1 y=2

array([1., 2.])